name: GitHub Syncronisation Knowledge Base
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - name: Sync Data
         with: # Set the secret as an input
          super_secret: ${{ secrets.MONGO_URL }}
         env: # Or as an environment variable
          super_secret: ${{ secrets.MONGO_URL }}
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
         with:
           node-version: '14.x'
       - run: npm install
       - run: node index.js
